---
title: 今更Eagle7のファイル構造を研究してみた
abstract: きっとN番煎じ
circle: KY技研
author: "@_K4UKI_"
comiket: 技術書典4
year: 2018
publisher: キンコーズオンラインで印刷製本（予定）
docrevision: "1.0"
front: images/animal-washi.png
verbcolored: false
...
